server.port=8080

java-explore-with-me.url=http://stats-server:9090

spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewm-main
spring.datasource.username=postgres
spring.datasource.password=postgres